#!/bin/bash
ALX schoolroot@f6fc1ee8d364:~/alx-zero_day/0x03-git/bash# ls
ALX schoolroot@f6fc1ee8d364:~/alx-zero_day/0x03-git/bash# ls   [D[D[D[D[D[D
root@f6fc1ee8d364:~/alx-zero_day/0x03-git/bash# cat > school
